changed add table column files to use function

diff --git a/addTableColumn b/addTableColumn
--- a/addTableColumn
+++ b/addTableColumn
@@ -1,77 +1,100 @@
 #! /usr/bin/bash
-# This script creates a table in the specified database.
-dbName=$1
-tableName=$2
-if [[ -z $dbName || -z $tableName ]]
-then
-    echo "internal error: database name or table name is not provided"
-    exit 1
-fi
-# if [[ $# > 2 ]] --> a case later to be the query
-echo "Creating table '$tableName' in database '$dbName'..."
-pk=0
-while true
-do
-    read -p "Enter column name (or type '0' to finish): " columnName
-    if [[ $columnName == "0" ]]
-    then
-        if [[ $pk -eq 0 ]]
-        then
-            echo "You must define at least one primary key!"
-            read -r -p "Press any key to try again..." -n1 -s
+
+create_table() {
+    echo "Creating table '$tableName' in database '$dbName'..."
+
+    while true; do
+        clear
+        read -p "Enter column name (or type '0' to finish): " columnName
+        if [[ "$columnName" == "0" ]]; then
+            if [[ $pk -eq 0 ]]; then
+                echo "You must define at least one primary key!"
+                pause
+                continue
+            fi
+            echo "Finished creating table '$tableName'."
+            break
+        fi
+
+        if ! validate_column_name "$columnName"; then
+            pause
             continue
         fi
-        echo "Finished creating table '$tableName'."
-        break
-    fi
-    # If input is empty (user just pressed Enter)
-    if [[ -z "$columnName" ]] 
-    then
+        ./checkForRepeatedColumnName $dbName $tableName $columnName
+        if [[ $? -eq 0 ]];  # Check if the column name already exists
+        then
+            echo "Column $columnName already exists in table $tableName. Please choose a different name."
+            pause
+            continue
+        fi
+
+        choose_column_type $dbName $tableName $columnName
+    done
+}
+
+validate_column_name() {
+    local name=$1
+
+    if [[ -z "$name" ]]; then
         echo "You must enter a column name!"
-        read -r -p "Press any key to try again..." -n1 -s
-        continue
+        return 1
     fi
-    resultOfInputValidation=$(./inputValidator CHARS_ONLY $columnName)
-    if [[ $resultOfInputValidation != 0 ]]
-    then
+
+    local result
+    result=$(./inputValidator CHARS_ONLY "$name")
+    if [[ "$result" != "0" ]]; then
         echo "Column name should be any combination of letters from A to Z or a to z"
-        read -r -p "Press any key to try again..." -n1 -s
-        continue
+        return 1
     fi
-    ./checkForRepeatedColumnName "$dbName" "$tableName" "$columnName"
-    if [[ $? -eq 0 ]]
-    then
-        echo "Column '$columnName' already exists in table '$tableName'. Please choose a different name."
-        read -r -p "Press any key to try again..." -n1 -s
-        echo
-        continue
-    fi
-    ps3="Choose the type of column '$columnName': "
-    select columnType in "INT" "BOOLEAN" "STRING"
-    do
+
+    return 0
+}
+
+choose_column_type() {
+    columnName=$3
+
+    PS3="Choose the type of column '$columnName': "
+    select columnType in "INT" "BOOLEAN" "STRING"; do
         case "$columnType" in
             "INT"|"BOOLEAN"|"STRING")
-                if [[ $pk -eq 0 ]]; then
-                    read -rp "Is this column a primary key? (yes/no): " isPrimaryKey
-                    if [[ $isPrimaryKey =~ ^[yY]([eE][sS])?$ ]]; then
-                        if [[ $columnType != "INT" ]]; then
-                            echo "Only INT type can be a primary key. Please choose another type."
-                            break
-                        fi
+                if [[ $pk -eq 0 && $columnType == "INT" ]]; then
+                    read -p "Is this column a primary key? (yes/no): " isPrimaryKey
+                    if [[ "$isPrimaryKey" =~ ^[yY]([eE][sS])?$ ]]
+                    then
                         pk=1
-                        echo "Column '$columnName' is set as primary key."
-                        echo "$columnName:PK" >> "mydb/$dbName/.$tableName.metadata"
+                        echo "Column $columnName is set as primary key."
+                        echo "$columnName:PK" >> "./mydb/$dbName/.$tableName.metadata"
                         break
                     fi
                 fi
-                echo "Adding column '$columnName' of type '$columnType' to table '$tableName'..."
-                echo "$columnName:$columnType" >> "mydb/$dbName/.$tableName.metadata"
+                echo "Adding column $columnName of type $columnType to table $tableName..."
+                echo "$columnName:$columnType" >> "./mydb/$dbName/.$tableName.metadata"
                 break
                 ;;
             *)
                 echo "Invalid column type. Please choose a valid type."
-                continue
                 ;;
         esac
     done
-done
+}
+
+pause() {
+    read -r -p "Press any key to try again..." -n1 -s
+    echo
+}
+
+# --- Main Execution ---
+
+if [[ $# -lt 2 ]]
+then
+    echo "internal error: database name or table name is not provided"
+    exit 1
+fi
+
+dbName=$1
+tableName=$2
+pk=0
+
+create_table $dbName $tableName
+pause
+clear
diff --git a/createTable b/createTable
--- a/createTable
+++ b/createTable
@@ -1,44 +1,70 @@
 #!/usr/bin/bash
 
-dbName=$1
+prompt_table_name() {
+    while true
+    do
+        read -p "Enter table name to create (or type '0' to go back): " tableName
 
-while true
-do
+        if [[ $tableName == "0" ]]; then
+            exit 1
+        fi
 
-    read -p "Enter table name to create (or type '0' to go back): " tableName
+        if ! validate_table_name $tableName; then
+            pause
+            continue
+        fi
 
-     if [[ $tableName == "0" ]]
-    then
+        if table_exists $dbName $tableName; then
+            echo "Table with the same name already exists. Choose another one!"
+            pause
+            continue
+        fi
+
+        break
+    done
+}
+
+validate_table_name() {
+    if [[ -z "$tableName" ]]; then
+        echo "You must enter a table name!"
+        return 1
+    fi
+
+    local result
+    result=$(./inputValidator CHARS_ONLY "$tableName")
+
+    if [[ $result != "0" ]]; then
+        echo "Table name should be any combination of letters from A to Z or a to z"
+        return 1
+    fi
+
+    return 0
+}
+
+table_exists() {
+    [[ -f "./mydb/$dbName/$tableName" ]]
+}
+
+pause() {
+    read -r -p "Press any key to try again..." -n1 -s
+    echo
+}
+
+create_table_files() {
+    touch "./mydb/$dbName/$tableName" "./mydb/$dbName/.$tableName.metadata"
+}
+
+main() {
+    dbName=$1
+    if [[ -z "$dbName" ]]; then
+        echo "Database name is required"
         exit 1
     fi
 
+    prompt_table_name
+    create_table_files
+    ./addTableColumn "$dbName" "$tableName"
+    exit 0
+}
 
-      # If input is empty (user just pressed Enter)
-    if [[ -z "$tableName" ]]; then
-        echo "You must enter a table name!"
-        read -r -p "Press any key to try again..." -n1 -s
-        continue
-    fi
-
-     resultOfInputValidation=$(./inputValidator CHARS_ONLY $tableName)
-
-    if [[ $resultOfInputValidation != 0 ]]
-    then
-        echo " Table name should be any combination of letters from A to Z or a to z"
-        continue
-    fi
-
-
-    if [[ -f ./mydb/$dbName/$tableName ]]
-    then
-        echo "Table with the same name already exits. Choose another one! "
-        read -r -p "Press any key to try again..." -n1 -s
-        continue
-
-    fi
-    break
-done
-
-touch mydb/$dbName/$fileName  mydb/$dbName/".$fileName.metadata"
-
-exit 0
+main $@
