refactored: fixed an error when there is no databases or tables
modified: listAllDB: now exits gracefully if no databases or tables are found with status code 1
modified: connectToDB: now exits gracefully if no databases are found with status code 1 returned from listAllDB
modified: insertToTable: now exits with error message if no tables are found
modified: updateInTable: now exits with error message if no tables are found

*removed logs directory as it is not needed anymore

diff --git a/connectToDB b/connectToDB
--- a/connectToDB
+++ b/connectToDB
@@ -14,7 +14,12 @@ do
     clear
     
     ./listAllDB
-    
+    if [[ $? -ne 0 ]]; then
+        echo -e "${RED}❌ [ Error ] Failed to list databases.${NC}"
+        read -n1 -rp "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -s
+        echo
+        exit 1
+    fi
 
     read -r -p $'\n📘 [ Info ] Enter database name to connect (or type "exit" to go back): ' dbName
    
