Implemented connectToDB, showTables, createTable files, made some modifications on almost all file and prepared stubs to work on them later

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,33 +1,57 @@
-#! /usr/bin/bash
+#!/usr/bin/bash
 
-echo 'Welcome to my_db project'
+echo "                |============================| "
+echo "                |Welcome To DBMS Bash Project| "
+echo "                |============================| "
+echo
 
-select action in CreatDb ListAllDb ConnectDb DropDb Exit
+while true 
 do
-    case $action in
-        CreatDb)
-            ./creatDB
-            if [[ $? -eq 0 ]]
-            then
-                echo your database created successfuly press 2 to connect to it or 1 to creat another or 3 to exit
-            else
-                echo failed to creat your Database press 1 to try again, 2 to connect to an existing one or 3 to exit
-            fi
-            ;;        
-        ListAllDb)
-            ./ListAllDb
-            ;;       
-        ConnectDb)
-            echo `./connectToDb`
-            ;;
-        DropDb)
-            echo work in progress
-            ;;            
-        Exit)
-            echo bye!
-            exit
-            ;;
-        *)
-            echo invalid input
-    esac
+    clear
+    PS3="Enter your choice (1-5): "
+    echo "Choose an action:"
+    select action in "Create a database" "List all databases" "Connect to a database" "Drop a database" "Exit DBMS"
+    do
+        case "$action" in
+            "Create a database")
+                ./createDB
+		if [[ $? -eq 0 ]]; then
+                    echo "Your database was created successfully!"
+                else
+                    echo "Failed to create your database."
+                fi
+                break
+                ;;
+
+            "List all databases")
+                ./listAllDB
+                break
+                ;;
+
+            "Connect to a database")
+               ./connectToDB
+                break
+                ;;
+
+            "Drop a database")
+                read -p "Enter the name of the database to delete: " dbname
+                ./dropDB "$dbname"
+                break
+                ;;
+
+            "Exit DBMS")
+                echo "Exitting.....!"
+                exit
+                ;;
+
+            *)
+                echo "Invalid input. Please choose a number from the menu."
+                ;;
+        esac
+    done
+
+    # Pause before returning to the menu
+    read -r -p "Press any key to return to the menu..." -n1 -s
+    echo
 done
+
