update now can update a different column than the one used to comparer to

diff --git a/UpdateRecord b/UpdateRecord
--- a/UpdateRecord
+++ b/UpdateRecord
@@ -7,17 +7,19 @@ YELLOW='\033[1;33m'
 BLUE='\033[0;36m'
 NC='\033[0m' # No Color
 
-# This script updates a specific entry in a table file.
-
+# ━━━━━━━━━━━━[ parsing input ]━━━━━━━━━━━━
 dbname=$1
 table=$2
-columnName=$3
+compareCol=$3
 Value=$4
 operator=$5
-newValue=$6
-columnIndex=$(./getColumnIndex "$dbname" "$table" "$columnName")
-if [[ -z "$columnIndex" || $? -ne 0 ]]; then
-  echo -e "${RED}❌ Column '$columnName' not found in table '$table'.${NC}"
+editCol=$6
+newValue=$7
+# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
+
+editColumnIndex=$(./getColumnIndex "$dbname" "$table" "$editCol")
+if [[ -z "$editColumnIndex" || $? -ne 0 ]]; then
+  echo -e "${RED}❌ Column '$editCol' not found in table '$table'.${NC}"
   exit 1
 fi
 
@@ -26,13 +28,13 @@ if [[ -z "$newValue" ]]; then
   exit 1
 fi
 ##
-if [[ -z "$Value" || -z "$operator" ]]; then
+if [[ -z "$Value" || -z "$operator" || -z "$compareCol" ]]; then
   #update all rows in the table
   Value='@'
   operator='!='
 fi
 ## check for > , < with only INTs
-columnType=$(./getType "$dbname" "$table" "$columnName")
+columnType=$(./getType "$dbname" "$table" "$compareCol")
 if [[ "$operator" == ">" || "$operator" == "<" ]] && [[ "$columnType" != "INT" ]]; then
   echo -e "${RED}❌ Invalid operator '$operator' for column type '$columnType'. Only INT columns can use > or < operators.${NC}"
   exit 1
@@ -40,8 +42,19 @@ fi
 
 tablePath="./mydb/$dbname/$table"
 metaPath="./mydb/$dbname/.$table.metadata"
-numberOfColumns=$(wc -l < $metaPath)
-matchedRows=$(./getRows "$dbname" "$table" "$columnName" "$Value" "$operator")
+
+# check if the column to be updated is a primary key
+isPK=0
+if grep -q "^$editCol:.*:1$" "$metaPath"; then
+    isPK=1    
+    ./pkCheck "$dbname" "$table" "$editColumnIndex" "$newValue"
+    if [ $? -eq 0 ]; then
+        echo -e "${RED}❌ Primary key value '$newValue' already exists. Update aborted.${NC}"
+        exit 1  
+    fi
+fi
+
+matchedRows=$(./getRows "$dbname" "$table" "$compareCol" "$Value" "$operator")
 
 if [[ $? -ne 0 ]]; then
   echo -e "${RED}❌ Error retrieving rows. Please check the inputs.${NC}"
@@ -57,36 +70,24 @@ fi
 # this is to avoid issues with line numbers changing after each update
 matchedRows=$(echo "$matchedRows" | tr ' ' '\n' | sort -r | tr '\n' ' ')
 
-## check if this column is primary key
-metaData="./mydb/$dbname/.$table.metadata"
-isPK=0
-if grep -q "^$columnName:.*:1$" "$metaData"; then
-    isPK=1
-    ./pkCheck "$dbname" "$table" "$columnIndex" "$newValue"
-    if [ $? -eq 0 ]; then
-        echo -e "${RED}❌ Primary key value '$newValue' already exists. Update aborted.${NC}"
-        exit 1  
-    fi
-fi
-
 #check if the entered value is valid for this column
-columnType=$(grep "^$columnName:" "$metaData" | cut -d: -f2)
+columnType=$(grep "^$editCol:" "$metaPath" | cut -d: -f2)
 inputValidatorResult=$(./inputValidator "$columnType" "$newValue")
 if [[ "$inputValidatorResult" != "0" ]]; then
-    echo -e "${RED}❌ Invalid value for column $columnName of type $columnType.${NC}"
+    echo -e "${RED}❌ Invalid value for column $editCol of type $columnType.${NC}"
     exit 1
 fi
 
-columnIndex=$(./getColumnIndex "$dbname" "$table" "$columnName")
-
 declare -i rowsAffected=0
+
+numberOfColumns=$(wc -l < $metaPath)
 
 for row in $matchedRows; do
 
     line=$(sed -n "${row}p" "$tablePath")
     newline=''
     for i in $(seq 1 $numberOfColumns); do
-    if [ $i -eq "$columnIndex" ]; then
+    if [ $i -eq "$editColumnIndex" ]; then
         newline+="$newValue:"
     else
         newline+=$(echo "$line" | cut -d':' -f"$i"):
